GameForum/Controllers/AddController.cs
using GameForum.Application.Interface;
using GameForum.Application.ViewModels.MergedVm;
using GameForum.Application.ViewModels.Paragraphs;
using GameForum.Application.ViewModels.Posts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GameForum.Web.Controllers
{
    [Authorize]
    public class AddController : Controller
    {
        private readonly IMergedService _mergedService;

        public AddController(IMergedService mergedService)
        {
            _mergedService = mergedService;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            var template = _mergedService.GetNewPostTemplate();
            return View(template);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(NewPostWithGenresVm newPost)
        {
            if (!ModelState.IsValid)
            {
                return View(newPost);
            }
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            newPost.Post.ForumUserId = claims.Value.ToString();
            var id = _mergedService.AddNewPost(newPost);
            return RedirectToAction("AddParagraph",new {postId = id });
        }

        [HttpGet]
        [Authorize]
        public IActionResult AddParagraph(int postId, bool firstParagraph = true)
        {
            var paragraph = new NewParagraphVm() { PostId = postId, FirstParagraph = firstParagraph };
            ViewBag.added = 0;
            return View(paragraph);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddParagraph(NewParagraphVm newParagraph)
        {
            _mergedService.AddNewParagraph(newParagraph);
            ViewBag.added = 1;
            return (RedirectToAction("AddParagraph", new { postId = newParagraph.PostId, firstParagraph = false }));
        }
    }
}

GameForum/Controllers/BlogController.cs
using GameForum.Application.Interface;
using GameForum.Application.ViewModels.Comments;
using GameForum.Application.ViewModels.Paragraphs;
using GameForum.Application.ViewModels.Posts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GameForum.Web.Controllers
{
    public class BlogController : Controller
    {
        private readonly IPostService _postService;
        public BlogController(IPostService postService)
        {
            _postService = postService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var posts = _postService.GetPosts(1,"");

            return View(posts);
        }

        [HttpPost]
        public IActionResult Index(int? page, string searchString)
        {
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            if (!page.HasValue)
            {
                page = 1;
            }

            var posts = _postService.GetPosts(page.Value, searchString);

            return View(posts);
        }

        [HttpGet]
        public IActionResult Read(int id)
        {
            var post = _postService.GetPost(id);

            return View(post);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Read(PostToReadVm postWithComment)
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var comment = postWithComment.NewComment;
            comment.ForumUserId = claims.Value.ToString();
            _postService.AddCommentToPost(comment);
            return RedirectToAction("Read", new { id = postWithComment.Id });
        }

        public IActionResult ReportPost(int postId)
        {
            _postService.ReportPost(postId);
            return RedirectToAction("Read", (new {id = postId }));
        }

        public IActionResult MyPosts()
        {
            var posts = _postService.GetUserPosts(User.FindFirstValue(ClaimTypes.NameIdentifier), 1,"");

            ViewBag.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            return View(posts);
        }

        [HttpPost]
        public IActionResult MyPosts(int? page, string searchString)
        {
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            if (!page.HasValue)
            {
                page = 1;
            }
            ViewBag.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var posts = _postService.GetUserPosts(User.FindFirstValue(ClaimTypes.NameIdentifier), page.Value, searchString);

            return View(posts);
        }


        [HttpGet]
        public IActionResult EditPost(int postId)
        {
            if (!_postService.CheckAuthor(postId,User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                return RedirectToAction("Index");
            }
            var post = _postService.GetPostForUpdate(postId);

            return View(post);
        }

        [HttpPost]
        public IActionResult EditPost(PostForUpdateVm post)
        {
            _postService.UpdatePost(post);
            return RedirectToAction("Read", (new { id = post.Id }));
        }

        public IActionResult EditParagraph(int postId,int paragraphId)
        {
            if (!_postService.CheckAuthor(postId, User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                return RedirectToAction("Index");
            }
            if (!_postService.CheckParagraph(postId, paragraphId))
            {
                return RedirectToAction("Index");
            }

            var paragraph = _postService.GetParagraph(paragraphId);

            return View(paragraph);
        }

        [HttpPost]
        public IActionResult EditParagraph(ParagraphDetailsVm paragraph)
        {
            var postId =_postService.UpdateParagraph(paragraph);
            return RedirectToAction("EditPost", (new { postId = postId }));
        }

        public IActionResult AddParagraph(int postId)
        {
            var paragraph = new NewParagraphVm()
            {
                PostId = postId,
                
            };
            return View(paragraph);
        }

        [HttpPost]
        public IActionResult AddParagraph(NewParagraphVm paragraph)
        {
            _postService.AttachParagraphToPost(paragraph);
            return RedirectToAction("EditPost", (new { postId = paragraph.PostId }));
        }

        public IActionResult DeletePost(int postId)
        {
            _postService.DeletePost(postId);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteParagraph(int paragraphId, int postId)
        {
            _postService.DeleteParagraph(paragraphId);
            return RedirectToAction("EditPost", (new { postId = postId }));
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

GameForum/Controllers/UserController.cs
using GameForum.Application.Interface;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GameForum.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var users = _userService.GetUsers(1,"");
            //var claimIdentity = (ClaimsIdentity)User.Identity;
            //var claims = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            //if (claims != null)
            //{
            //    ViewData["userId"] = claims.Value.ToString();
            //}
            //else
            //{
            //    ViewData["userId"] = "";
            //}
            return View(users);
        }

        [HttpPost]
        public IActionResult Index(int? page, string searchString)
        {
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            if (!page.HasValue)
            {
                page = 1;
            }

            var users = _userService.GetUsers(page.Value,searchString);
            return View(users);
        }

        public IActionResult UserDetails(string id)
        {

            var userDetails =_userService.GetUserDetails(id);

            return View(userDetails);
        }
    }
}

GameForum/Views/Blog/AddParagraph.cshtml
@model GameForum.Application.ViewModels.Paragraphs.NewParagraphVm

@{
    ViewData["Title"] = "AddParagraph";
}

<h1>AddParagraph</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddParagraph">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <input type ="hidden" asp-for="PostId" class="form-control" value="@Model.PostId" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

GameForum/Views/Blog/Create.cshtml
@model GameForum.Application.ViewModels.Posts.NewPostVm

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>NewPostVm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GameForum/Views/Blog/EditParagraph.cshtml
@model GameForum.Application.ViewModels.Paragraphs.ParagraphDetailsVm

@{
    ViewData["Title"] = "EditParagraph";
}

<h1>EditParagraph</h1>

<h4>ParagraphDetailsVm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditParagraph">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control" />
            <input type="hidden" asp-for="PostId" class=" form-control" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

GameForum/Views/Blog/EditPost.cshtml
@model GameForum.Application.ViewModels.Posts.PostForUpdateVm

@{
    ViewData["Title"] = "EditPost";
}

<h1>EditPost</h1>

<a class="btn btn-danger" asp-action="DeletePost"
   asp-route-postId="@Model.Id">Delete Post</a>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPost">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @foreach (var item in Model.Paragraphs)
            {
                <div class="form-group">
                    <h3>@item.Title</h3>
                </div>
                <div class="form-group">
                    <p>@item.Text</p>
                </div>
                <div class="row">
                    <a class="btn btn-warning" asp-action="EditParagraph"
                       asp-route-paragraphId="@item.Id" asp-route-postId="@Model.Id">Edit</a> |
                    <a class="btn btn-danger" asp-action="DeleteParagraph"
                       asp-route-paragraphId="@item.Id" asp-route-postId="@Model.Id">Delete</a>

                </div>
                <br />
            }
            <div class="form-group row">
                <a class="btn btn-info" asp-action="AddParagraph"
                   asp-route-postId="@Model.Id">Add Paragraph</a>
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

GameForum/Views/Blog/Index.cshtml
@model GameForum.Application.ViewModels.Posts.ListPostForListVm

@{
    ViewData["Title"] = "Index";
}


<form asp-controller="Blog" asp-action="Index" method="post">
<p>
    <a class="btn btn-info" asp-controller="Add" asp-action="Index">Create New</a>
</p>

<div class="row">
    <input type="text" asp-for="SearchString" name="searchString" id="searchString" />
    <input type="submit" value="Search"/>
</div>
<table class="table">
    <thead>
        <tr>

            <th>
                Title
            </th>
            <th>
                Description
            </th>
            <th>
                Genre
            </th>
            <th>
                Created
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Posts)
{
        <tr>
            <td>
                @Html.ActionLink(item.Title,"Read", new {id = item.Id})
                <br />
                @Html.ActionLink(item.Author.UserName,"UserDetails", "User", new {id = item.Author.Id})
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre.Name)
            </td>
            <td>
                @item.CreateTime.ToLongDateString()
            </td>
        </tr>
}
    </tbody>
</table>

<div class="row">
    <table>
        <tr>
            @for (int i = 1; i <= Math.Ceiling(Model.Count/20.0f); i++)
            {
                <td>
                    @if(i == Model.CurrentPage)
                    {
                        <span class="btn">@i</span>
                    }
                    else
                    {
                        <a class="btn btn-info" href="javascript:PageCLick(@i)">@i</a>
                    }
                </td>
            }
        </tr>
    </table>
    <input type="hidden" id="page" name="page" />
</div>
</form>

@section Scripts
{
    <script type="text/javascript">
        function PageCLick(index) {
            document.getElementById("page").value = index;
            document.forms[0].submit();
        }
    </script>
}

GameForum/Views/Blog/MyPosts.cshtml
@model GameForum.Application.ViewModels.Posts.ListUserPostForListVm

@{
    ViewData["Title"] = "MyPosts";
}

<h1>My Posts</h1>

<form asp-action="MyPosts" method="post">

    <div class="row">
        <input type="text" asp-for="SearchString" name="searchString" id="searchString" />
        <input type="submit" value="Search" />
    </div>

    <table class="table">
        <thead>
            <tr>

                <th>
                    Title
                </th>
                <th>
                    Description
                </th>
                <th>
                    Status
                </th>
                <th>
                    CreateTime
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.PostList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @if (item.IsBanned)
                        {
                            <p>Banned</p>
                        }
                        else
                        {
                            <p>Online</p>
                        }
                    </td>
                    <td>
                        @item.CreateTime.ToLongDateString()
                    </td>
                    <td>
                        <a class="btn btn-success" asp-action="Read"
                           asp-route-id="@item.Id">Read</a>
                        @if (ViewBag.UserId == Model.UserId)
                        {

                            <a class="btn btn-warning" asp-action="EditPost"
                               asp-route-postId="@item.Id">Edit</a>
                        }
                        @if (ViewBag.UserId == Model.UserId)
                        {
                            <a class="btn btn-danger" asp-action="DeletePost"
                               asp-route-postId="@item.Id">Delete</a>
                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="row">
        <table>
            <tr>
                @for (int i = 1; i <= Math.Ceiling(Model.Count / 20.0f); i++)
                {
                    <td>
                        @if (i == Model.CurrentPage)
                        {
                            <span class="btn">@i</span>
                        }
                        else
                        {
                            <a class="btn btn-info" href="javascript:PageCLick(@i)">@i</a>
                        }
                    </td>
                }
            </tr>
        </table>
        <input type="hidden" id="page" name="page" />
        <input type="hidden" id="userId" name="UserId" value="@Model.UserId" />
    </div>
</form>

@section Scripts
{
    <script type="text/javascript">
        function PageCLick(index) {
            document.getElementById("page").value = index;
            document.forms[0].submit();
        }
    </script>
}

GameForum/Views/Blog/Read.cshtml
@model GameForum.Application.ViewModels.Posts.PostToReadVm

@{
    ViewData["Title"] = "Read";
}

<h1 class="text-center">@Model.Title</h1>
<h5>@Model.Genre.Name</h5>
<h6>@Model.Author.UserName</h6>
@if (Model.IsChecked)
{
    <h5>
        Post is checked
    </h5>
}
<div>
    <hr />
    <dl class="row">
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateTime)
        </dd>
    </dl>
</div>

<ul class="list-group list-group-flush w-100">
    @foreach (var item in Model.Paragraphs)
    {
        <li class="list-group-item">
            <h2 class="text-center ">@item.Title</h2>
            <br />
            <p class="text-center">@item.Text</p>
        </li>
    }
</ul>
<br />
<h5>
    @if (!Model.IsChecked)
    {
        <a class="btn btn-warning" asp-action="ReportPost"
           asp-route-postId="@Model.Id">Report Post</a>
    }
</h5>
<br />
<h2>
    Comments:
</h2>
<br />
@if (User.Identity.IsAuthenticated)
{
<form asp-action="Read">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input asp-for="Id" type="hidden"value="@Model.Id"/>
    <input asp-for="NewComment.PostId" type ="hidden" value="@Model.Id"/>
    <div class="form-group">
        <label class="control-label">Comment:</label>
        <textarea asp-for="NewComment.Text" class="form-select container-fluid" rows="2"></textarea>
        <span asp-validation-for="NewComment.Text" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Comment" class="btn btn-primary float-right" />
    </div>
</form>
}
<div>

</div>
<div>
    <table class="table-hover table-responsive">
        <tbody>
            @foreach (var item in Model.Comments)
            {
                <tr class="border">
                    <td>
                        <a class="btn btn-outline-info" asp-action="UserDetails" asp-controller="User"
                           asp-route-id="@item.Author.Id">@item.Author.UserName</a>
                        <br />
                        @item.CreateTime.ToShortDateString()
                    </td>
                    <td class="text-left container-fluid">
                        @item.Text
                        <br />
                    </td>
                    </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to post list</a>
</div>